const singleWord = [
  {
    id: 1,
    word: 'Apple',
    pos: 'n.',
    mean: '蘋果',
    color: 'red',
    status: true,
    option: ['蘋果', '香蕉', '梨子', '番茄'],
    answer: '1',
  },
  {
    id: 2,
    word: 'Banana',
    pos: 'n.',
    mean: '香蕉',
    color: 'red',
    status: true,
    option: ['蘋果', '香蕉', '梨子', '番茄'],
    answer: '2',
  },
  {
    id: 3,
    word: 'Orange',
    pos: 'n.',
    mean: '橘子',
    color: 'red',
    status: false,
    option: ['蘋果', '橘子', '梨子', '番茄'],
    answer: '2',
  },
  {
    id: 4,
    word: 'pear',
    pos: 'n.',
    mean: '梨子',
    color: 'red',
    status: false,
    option: ['蘋果', '橘子', '梨子', '番茄'],
    answer: '3',
  },
  {
    id: 5,
    word: 'run',
    pos: 'v.',
    mean: '跑步',
    color: 'purple',
    status: false,
    option: ['跳躍', '走路', '爬行', '跑步'],
    answer: '4',
  },
];

export default singleWord;
